export enum SpecialitesMedicales {
  // Spécialités cliniques
  CARDIOLOGIE = "Cardiologie",
  PNEUMOLOGIE = "Pneumologie",
  GASTROENTEROLOGIE = "Gastro-entérologie",
  NEPHROLOGIE = "Néphrologie",
  ENDOCRINOLOGIE_DIABETOLOGIE = "Endocrinologie et Diabétologie",
  RHUMATOLOGIE = "Rhumatologie",
  DERMATOLOGIE = "Dermatologie",
  NEUROLOGIE = "Neurologie",
  PSYCHIATRIE = "Psychiatrie",
  MEDECINE_INTERNE = "Médecine Interne",
  MEDECINE_GENERALE = "Médecine Générale",
  MEDECINE_GERIATRIQUE = "Médecine Gériatrique",
  PEDIATRIE = "Pédiatrie",
  ALLERGOLOGIE_IMMUNOLOGIE = "Allergologie et Immunologie",
  ONCOLOGIE = "Oncologie",
  HEMATOLOGIE = "Hématologie",
  INFECTIOLOGIE = "Infectiologie",
  MEDECINE_PHYSIQUE_REEDUCATION = "Médecine Physique et Réadaptation",

  // Spécialités chirurgicales
  CHIRURGIE_GENERALE = "Chirurgie Générale",
  CHIRURGIE_CARDIAQUE = "Chirurgie Cardiaque",
  CHIRURGIE_THORACIQUE = "Chirurgie Thoracique",
  CHIRURGIE_VASCULAIRE = "Chirurgie Vasculaire",
  CHIRURGIE_ORTHOPEDIQUE = "Chirurgie Orthopédique",
  NEUROCHIRURGIE = "Neurochirurgie",
  CHIRURGIE_PLASTIQUE_RECONSTRUCTRICE = "Chirurgie Plastique et Reconstructrice",
  CHIRURGIE_PEDIATRIQUE = "Chirurgie Pédiatrique",
  CHIRURGIE_DIGESTIVE = "Chirurgie Digestive",
  CHIRURGIE_MAXILLO_FACIALE = "Chirurgie Maxillo-Faciale",
  CHIRURGIE_GYNECOLOGIQUE = "Chirurgie Gynécologique",
  CHIRURGIE_UROLOGIQUE = "Chirurgie Urologique",
  CHIRURGIE_OPHTALMOLOGIQUE = "Chirurgie Ophtalmologique",
  CHIRURGIE_ORL = "Chirurgie ORL",

  // Autres spécialités médicales
  ANESTHESIOLOGIE = "Anesthésiologie",
  RADIOLOGIE = "Radiologie",
  MEDECINE_NUCLEAIRE = "Médecine Nucléaire",
  PATHOLOGIE = "Pathologie",
  GENETIQUE_MEDICALE = "Génétique Médicale",
  TOXICOLOGIE = "Toxicologie",
  MEDECINE_URGENCE = "Médecine d’Urgence",
  MEDECINE_TRAVAIL = "Médecine du Travail",
  MEDECINE_LEGALE = "Médecine Légale",
  SANTE_PUBLIQUE = "Santé Publique",
  MEDECINE_TROPICALE = "Médecine Tropicale",
  EPIDEMIOLOGIE = "Épidémiologie",
}
